[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
errors = { path = "../errors" }
derive_more.workspace = true
serde.workspace = true
chrono.workspace = true
bson.workspace = true